<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>hcde-pregame-guest</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HCDE.Net.Core\HCDE.Net.Core.csproj" />
    <ProjectReference Include="..\HCDE.Net.Pregame\HCDE.Net.Pregame.csproj" />
  </ItemGroup>

</Project>
