# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...4.1)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS re2c lemon zipdir)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target re2c
add_executable(re2c IMPORTED)

# Create imported target lemon
add_executable(lemon IMPORTED)

# Create imported target zipdir
add_executable(zipdir IMPORTED)

# Import target "re2c" for configuration "Debug"
set_property(TARGET re2c APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(re2c PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Users/user/DoomConnector6/HCDE/tools/re2c/Debug/re2c.exe"
  )

# Import target "lemon" for configuration "Debug"
set_property(TARGET lemon APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(lemon PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Users/user/DoomConnector6/HCDE/tools/lemon/Debug/lemon.exe"
  )

# Import target "zipdir" for configuration "Debug"
set_property(TARGET zipdir APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(zipdir PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Users/user/DoomConnector6/HCDE/tools/zipdir/Debug/zipdir.exe"
  )

# Import target "re2c" for configuration "Release"
set_property(TARGET re2c APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(re2c PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Users/user/DoomConnector6/HCDE/tools/re2c/Release/re2c.exe"
  )

# Import target "lemon" for configuration "Release"
set_property(TARGET lemon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(lemon PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Users/user/DoomConnector6/HCDE/tools/lemon/Release/lemon.exe"
  )

# Import target "zipdir" for configuration "Release"
set_property(TARGET zipdir APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(zipdir PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Users/user/DoomConnector6/HCDE/tools/zipdir/Release/zipdir.exe"
  )

# Import target "re2c" for configuration "MinSizeRel"
set_property(TARGET re2c APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(re2c PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/user/DoomConnector6/HCDE/tools/re2c/MinSizeRel/re2c.exe"
  )

# Import target "lemon" for configuration "MinSizeRel"
set_property(TARGET lemon APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(lemon PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/user/DoomConnector6/HCDE/tools/lemon/MinSizeRel/lemon.exe"
  )

# Import target "zipdir" for configuration "MinSizeRel"
set_property(TARGET zipdir APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(zipdir PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/user/DoomConnector6/HCDE/tools/zipdir/MinSizeRel/zipdir.exe"
  )

# Import target "re2c" for configuration "RelWithDebInfo"
set_property(TARGET re2c APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(re2c PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/user/DoomConnector6/HCDE/tools/re2c/RelWithDebInfo/re2c.exe"
  )

# Import target "lemon" for configuration "RelWithDebInfo"
set_property(TARGET lemon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(lemon PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/user/DoomConnector6/HCDE/tools/lemon/RelWithDebInfo/lemon.exe"
  )

# Import target "zipdir" for configuration "RelWithDebInfo"
set_property(TARGET zipdir APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(zipdir PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/user/DoomConnector6/HCDE/tools/zipdir/RelWithDebInfo/zipdir.exe"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
