namespace HCDE.MapLoader;

public enum AcsPcode : int
{
    Nop = 0,
    Terminate = 1,
    Suspend = 2,
    PushNumber = 3,
    Lspec1 = 4,
    Lspec2 = 5,
    Lspec3 = 6,
    Lspec4 = 7,
    Lspec5 = 8,
    Lspec1Direct = 9,
    Lspec2Direct = 10,
    Lspec3Direct = 11,
    Lspec4Direct = 12,
    Lspec5Direct = 13,
    Add = 14,
    Subtract = 15,
    Multiply = 16,
    Divide = 17,
    Modulus = 18,
    Eq = 19,
    Ne = 20,
    Lt = 21,
    Gt = 22,
    Le = 23,
    Ge = 24,
    AssignScriptVar = 25,
    AssignMapVar = 26,
    AssignWorldVar = 27,
    PushScriptVar = 28,
    PushMapVar = 29,
    PushWorldVar = 30,
    Goto = 52,
    IfGoto = 53,
    Drop = 54,
    Delay = 55,
    DelayDirect = 56,
    RandomDirect = 58,
    ThingCountDirect = 60,
    TagWaitDirect = 62,
    PolyWaitDirect = 64,
    ChangeFloorDirect = 66,
    ChangeCeilingDirect = 68,
    Restart = 69,
    EndPrintBold = 101,
}
